stages:
  train_model:
    cmd: python3 train_model.py --config=params.yaml
    params:
    - train
    outs:
    - results/metric_data.pkl
    metrics:
    - results/results.json:
        cache: false
