load_data:
  root: 
    /home/hoawenlo/Programming/Python/pytorch_practice/cnn_dvc_project/data/cifar-100-python
  train: true
  val: false

prepare_data:
  batchsize: 32
  shuffle: true

train:
  torch_params:
    model: convnet
    loss_fn: CrossEntropyLoss
    optimiser: Adam
  learning_rate: 0.001
  n_epochs: 8
  training_log_verboseness: 1

export_data:
  dst_filepath: /home/hoawenlo/Programming/Python/pytorch_practice/cnn_dvc_project/results/
  json_filepath: 
    /home/hoawenlo/Programming/Python/pytorch_practice/cnn_dvc_project/results/results.json
